// <auto-generated />
namespace Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPictureidToPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPictureidToPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201605141640516_AddPictureidToPerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
